[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/book"
  to = "https://landing-page-workflow.netlify.app/apply.html"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200